swagger: '2.0'
info:
  version: "1.0.1"
  title: 'CardMaker API'
  description: 'CardMaker API'

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: consumers
  description: Operations available to regular consumers

# paths
paths:
  /addCard:
    post:
      tags:
      - consumers
      summary: create a new card
      operationId: requestAddCard
      description: Requests to create a new card
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: AddCardRequest
        description: Create a new card
        schema:
          $ref: '#/definitions/AddCardRequest'
      responses:
        200:
          description: new card created
          schema:
            $ref: '#/definitions/AddCardResponse'
        400:
          description: invalid input, object invalid
        409:
          description: valid input
          
  /delCard:
    post:
      tags:
      - consumers
      summary: delete a specific card
      operationId: requestDelCard
      description: Requests to delete a specific card
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DelCardRequest
        description: delete a card
        schema:
          $ref: '#/definitions/DelCardRequest'
      responses:
        200:
          description: card deleted
        400:
          description: invalid input, object invalid
        409:
          description: valid input
  
          
  /updateCard:
    post:
      tags:
      - consumers
      summary: update a specific card
      operationId: requestUpdateCard
      description: Requests to update a specific card
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: UpdateCardRequest
        description: Update a new card
        schema:
          $ref: '#/definitions/UpdateCardRequest'
      responses:
        200:
          description: card updated
          schema:
            $ref: '#/definitions/UpdateCardResponse'
        400:
          description: invalid input, object invalid
        409:
          description: valid input
  /getCard:
    post:
      tags:
      - consumers
      summary: get a card according to id
      operationId: getCard
      description: Requests to get a card
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: ListCardRequest
        description: get a card
        schema:
          $ref: '#/definitions/getCardRequest'
      responses:
        200:
          description: successfully get a card
          schema:
            $ref: '#/definitions/getCardResponse'
        400:
          description: not a single card found 
        409:
          description: valid input 
  /dupilicateCard:
    post:
      tags:
      - consumers
      summary: duplicate a specific card
      operationId: requestDumplicateCard
      description: Requests to duplicate a specific card
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DuplicateCardRequest
        description: Duplicate a specific card
        schema:
          $ref: '#/definitions/DuplicateCardRequest'
      responses:
        200:
          description: card duplicated
          schema:
            $ref: '#/definitions/DuplicateCardResponse'
        400:
          description: invalid input, object invalid
        409:
          description: valid input
          
  /updateText:
    post:
      tags:
      - consumers
      summary: update the text on card
      operationId: requestUpdateText
      description: Requests to update text
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: UpdateTextRequest
        description: Update text
        schema:
          $ref: '#/definitions/UpdateTextRequest'
      responses:
        200:
          description: text updated
          schema:
            $ref: '#/definitions/UpdateTextResponse'
        400:
          description: invalid input, object invalid
        409:
          description: valid input
  
  /updateImage:
    post:
      tags:
      - consumers
      summary: update a specific image
      operationId: requestUpdateImage
      description: Requests to update image
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: UpdateImageRequest
        description: Update image, image base64 encoded
        schema:
          $ref: '#/definitions/UpdateImageRequest'
      responses:
        200:
          description: image updated
          schema:
            $ref: '#/definitions/UpdateImageResponse'
        400:
          description: invalid input, object invalid
        409:
          description: valid input
  /delImage:
    post:
      tags:
      - consumers
      summary: delete image
      operationId: requestDeleteImage
      description: Requests to delete a specific image
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DelImageRequest
        description: delete a image
        schema:
          $ref: '#/definitions/DelImageRequest'
      responses:
        200:
          description: image deleted
        400:
          description: invalid input, object invalid
        409:
          description: valid input
          
  /delText:
    post:
      tags:
      - consumers
      summary: delete text
      operationId: requestDeleteText
      description: Requests to delete text
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DelTextRequest
        description: Delete text
        schema:
          $ref: '#/definitions/DelTextRequest'
      responses:
        200:
          description: text deleted
        400:
          description: invalid input, object invalid
        409:
          description: valid input
          
  
  
  /ListExsitingImage:
    get:
      tags:
      - consumers
      summary: list all images
      operationId: requestLoadImage
      description: Requests to list all images, return Base64 encoded string
      produces:
      - application/json
      parameters:
      - in: body
        name: ListCardRequest
        description: list all images on a card
        schema:
          type: integer
      responses:
        200:
          description: all images listed
          schema:
            type: array
            items:
              $ref: '#/definitions/ListExsitingImageResponse'
        400:
          description: not a single card found 
        409:
          description: valid input
          
  /listCard:
    get:
      tags:
      - consumers
      summary: list all cards
      operationId: requestlistCard
      description: Requests to list all cards
      produces:
      - application/json
      parameters:
      - in: body
        name: ListCardRequest
        description: list all cards
        schema:
          type: integer
      responses:
        200:
          description: all cards listed
          schema:
            type: array
            items:
              $ref: '#/definitions/ListCardResponse'
        400:
          description: not a single card found 
        409:
          description: valid input
  
  /saveCard:
    post:
      tags:
      - consumers
      summary: save a specific card
      operationId: requestSaveCard
      description: Requests to save a specific card
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DuplicateCardRequest
        description: Duplicate a specific card
        schema:
          $ref: '#/definitions/SaveCardRequest'
      responses:
        200:
          description: card saved
          schema:
            $ref: '#/definitions/SaveCardResponse'
        400:
          description: invalid input, object invalid
        409:
          description: valid input

  
  
  /getImage:
    post:
      tags:
      - consumers
      summary: get images on a card
      operationId: getImage
      description: Requests to show images
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: getImageRequest
        description: get image on a card
        schema:
          $ref: '#/definitions/getImageRequest'
      responses:
        200:
          description: show images
          schema:
            $ref: '#/definitions/getImageResponse'
        400:
          description: not a single image found 
        409:
          description: valid input
  
  /getText:
    post:
      tags:
      - consumers
      summary: get text on a card
      operationId: getText
      description: Requests to list text on cards
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: ListCardRequest
        description: list all texts
        schema:
          $ref: '#/definitions/getTextRequest'
      responses:
        200:
          description: all text showed
          schema:
            $ref: '#/definitions/getTextResponse'
        400:
          description: not a single word found 
        409:
          description: valid input
    
definitions:
   
  AddCardResponse:
      type: object
      required:
      - id
      - name
      - eventtype
      - recipient
      - page
      properties:
        id:
          type: string
        name:
          type: string
        eventtype:
          type: string
        recipient:
          type: string
        page:
          type: array
          items:
            $ref: '#/definitions/page'

  page:
    type: string
  
  AddCardRequest:
      type: object
      required:
      - id
      - name
      - eventtype
      - recipient
      properties:
        id:
          type: string
        name:
          type: string
        eventtype:
          type: string
        recipient:
          type: string
  
  DelCardRequest:
    type: object
    required:
    - id
    properties:
      id:
        type: string
  
          
  UpdateCardRequest:
      type: object
      required:
      - name
      - eventtype
      - recipient
      properties:
        name:
          type: string
        eventtype:
          type: string
        recipient:
          type: string
  
  UpdateCardResponse:
    type: object
    required:
    - name
    - eventtype
    - recipient
    properties:
      name:
        type: string
      eventtype:
        type: string
      recipient:
        type: string
  
  UpdateTextRequest:
      type: object
      required:
      - id
      - text
      - page
      - font
      - textsize
      - location
      properties:
        id:
          type: string
        text:
          type: string
        page:
          type: string
        font:
          type: string
        textsize:
          type: string
        location:
          type: string
  UpdateTextResponse:
      type: object
      required:
      - id
      - text
      - page
      - font
      - textsize
      - location
      properties:
        id:
          type: string
        text:
          type: string
        page:
          type: string
        font:
          type: string
        textsize:
          type: string
        location:
          type: string  
  
  
  
  UpdateImageRequest:
    type: object
    required:
    - id
    - page
    - size
    - location
    - imagepath
    - image
    properties:
      id:
        type: string
      page:
        type: string
      size:
        type: string
      location:
        type: string
      imagepath:
        type: string
      image:
        type: string
        
  UpdateImageResponse:
    type: object
    required:
    - id
    - page
    - size
    - location
    - imagepath
    - image
    properties:
      id:
        type: string
      page:
        type: string
      size:
        type: string
      location:
        type: string
      imagepath:
        type: string
      image:
        type: string
  
  
  DelImageRequest:
      type: object
      required:
      - id
      - page
      - image
      properties:
        id:
          type: string
        page:
          type: string
        image:
          type: string
  
  DelTextRequest:
    type: object
    required:
    - id
    - page
    - text
    properties:
      id:
        type: string
      page:
        type: string
      text:
        type: string
      
  
          
  DuplicateCardRequest:
      type: object
      required:
      - id
      - recipient
      - eventtype
      properties:
        id:
          type: string
        recipient:
          type: string
        eventtype:
          type: string
        
  DuplicateCardResponse:
      type: object
      required:
      - id
      - recipient
      - eventtype
      properties:
        id:
          type: string
        recipient:
          type: string
        eventtype:
          type: string
          
  ListExsitingImageResponse:
      type: object
      required:
      - id
      - image
      properties:
        id:
          type: string
        image:
          type: string
  
  ListCardResponse:
      type: object
      required:
      - id
      properties:
        id:
          type: string
  
  
  SaveCardRequest:
      type: object
      required:
        - id
        - eventtype
        - recipient
        - page
      properties:
        id:
          type: string
        eventtype:
          type: string
        recipient:
          type: string
        page:
          type: string
        
  SaveCardResponse:
      type: object
      required:
        - id
        - eventtype
        - recipient
        - page
      properties:
        id:
          type: string
        eventtype:
          type: string
        recipient:
          type: string
        page:
          type: string          
  
  getCardRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    
  getCardResponse:
      type: object
      required:
      - id
      - name
      - eventtype
      - recipient
      - page
      properties:
        id:
          type: string
        name:
          type: string
        eventtype:
          type: string
        recipient:
          type: string
        page:
          type: array
          items:
            $ref: '#/definitions/page'
  
  getImageRequest:
      type: object
      required:
        - id
        - page
      properties:
        id:
          type: string
        page:
          type: string

  getImageResponse:
      type: object
      required:
      - id
      - page
      - size
      - location
      - imagepath
      - image
      properties:
        id:
          type: string
        page:
          type: string
        size:
          type: string
        location:
          type: string
        imagepath:
          type: string
        image:
          type: string
          

  getTextRequest:
      type: object
      required:
        - id
        - page
      properties:
        id:
          type: string
        page:
          type: string          
  getTextResponse:
      type: object
      required:
      - id
      - text
      - page
      - font
      - textsize
      - location
      properties:
        id:
          type: string
        text:
          type: string
        page:
          type: string
        font:
          type: string
        textsize:
          type: string
        location:
          type: string  

          
        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /WPI3/CardMaker/v1.0
schemes:
 - https
# Added by API Auto Mocking Plugin
basePath: /beichen-xing/AddText/1.0.0
